// Code generated by hero.
// source: C:\Projects\stemacademy_admissions\service\src\api\resetMessage.html
// DO NOT EDIT!
package main

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func ResetMessage(url string, token string, buffer *bytes.Buffer) {
	buffer.WriteString(`

<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.12/semantic.min.css"></link>
    </head>
    <body>
        <div class="ui basic very padded segment">
            <div class="ui container centered">
                <div class='ui compact segments'>
                    <div class="ui basic segment">
                        <h3 class="ui header">Password Reset</h3>
                    </div>
                    <div class="ui segment very padded">
                        <p>Please click the following link to reset your password:</p>
                        <h3 class="ui dividing header"></h3>
                        <a class="ui button" href="`)
	hero.EscapeHTML(url, buffer)
	buffer.WriteString(`/user/reset/`)
	hero.EscapeHTML(token, buffer)
	buffer.WriteString(`">Reset</a>
                    </div>
                </div>
            </div>
        </div>

        <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.js"></script>
    </body>
</html>`)

}
